name: github pages

on:
  push:
    branches:
      - zola
  pull_request:
    branches:
      - zola

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Zola
        run: ./scripts/ci.sh install

      - name: build resume
        run: cd resume/ && docker run --volume="$(pwd):/src" --rm realaravinth/resume:latest lualatex resume.tex

      - name: copy resume
        run: cp resume/resume.pdf static/realaravinth-resume.pdf

      - name: Build production website
        run: ./scripts/ci.sh build

      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/zola' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: zola-dist
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./public
