name: github pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Zola
        run: ./scripts/ci.sh install

      - name: build resume
        run: cd resume/ && docker run --volume="$(pwd):/src" --rm realaravinth/resume:latest lualatex resume.tex

      - name: copy resume
        run: cp resume/resume.pdf static/realaravinth-resume.pdf

      - name: Build production website
        run: ./scripts/ci.sh build

      - name: Deploy to github pages 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./public

      - name: deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'realaravinth/realaravinth' }}
        run: >-
          curl --location --request POST "https://deploy.batsense.net/api/v1/update" --header 'Content-Type: application/json' --data-raw "{ \"secret\": \"${{ secrets.DEPLOY_TOKEN }}\", \"branch\": \"gh-pages\" }"
